---
version: '3'
services:
  wms-server:
    hostname: wms-server
    image: wms-server
    ports:
      - 5101:5101
    volumes:
      - .:/code
    restart: unless-stopped
    environment:
      WMS_PORT: '5101'