---
version: '3'
services:
 wms_service:
    image: drivereu/test-bed-wms-service:1.0.7
    hostname: wmsservice
    environment:
      URL: http://${TESTBED_HOST}/wms/
      WMS_PORT: 5101
      WMS_HOST: wmsservice
      WMS_FOLDER: /server/data
      WMS_EXTERNAL_PORT: 5101
      WMS_EXTERNAL_HOST: http://${TESTBED_HOST}/wms/
      WMS_EXTERNAL_ADDRESS: http://${TESTBED_HOST}/wms/
      WMS_KAFKA_HOST: broker:${BROKER_PORT}
      WMS_SCHEMA_REGISTRY: http://schema_registry:${SCHEMA_REGISTRY_PORT}
      WMS_CORS_ORIGIN: https://oefen-veiligheidsregio.lcms.nl
      WMS_CORS_HEADERS: 'authorization, content-type'
    ports:
      - 5101:5101
    depends_on:
      - broker
      - schema_registry
    networks:
      - traefik-net
      - testbed-net
    deploy:
      labels:
        - "traefik.port=5101"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:${TESTBED_HOST};PathPrefix:/wms/"