---
version: '2'
services:
  wmsserver:
    build: https://github.com/DRIVER-EU/test-bed-wms-service.git#v0.0.2
    hostname: wmsserver
    ports:
      - "3355:3355"
    environment:
      WMS_PORT: '3355'
      GDAL_DATA: '/usr/share/gdal/2.2'
      PROJ_LIB: './src/nad'

